### ISSUE TITLE
Cannot import 'ImageNetPolicy'

### ISSUE THREAD

**Issue by rljahn** [PistonY/torch-toolbox#12]
Hi, I am new to the package. I want to use the ImageNetPolicy as one of the data transformation by 

`from torchtoolbox.transform import ImageNetPolicy`

But shows:

ImportError: cannot import name 'ImageNetPolicy'

How can I solve this? Thanks.

**Comment by PistonY** [comment]
Hi, try use this:
`from torchtoolbox.transform.autoaugment import ImageNetPolicy`

**Comment by rljahn** [comment]
Hi, I still cannot find it from the torchtoolbox folder. It seems like it's not registered (?)

![image](https://user-images.githubusercontent.com/72928406/104168049-58d22180-5438-11eb-9e3b-c26e15c9e2cc.png)

**Comment by PistonY** [comment]
I don't put `ImageNetPolicy` into `__init__` of transform.
So you need to import it from `autoaugment` module.
I've tried this way work for me.
```python
from torchtoolbox.transform.autoaugment import ImageNetPolicy
```
