### ISSUE TITLE
ImageLMDB subdir error

### ISSUE THREAD

**Issue by sailfish009** [PistonY/torch-toolbox#3]
set subdir=False, otherwise, 
subdir=os.path.isdir(db_path)

https://github.com/PistonY/torch-toolbox/compare/master...sailfish009:master

```

.local/lib/python3.7/site-packages/torchtoolbox/data/lmdb_dataset.py", line 23, in __init__
    readahead=False, meminit=False)
lmdb.Error: /tmp/train_lmdb/train_image.lmdb: Not a directory
```

**Comment by PistonY** [comment]
Could you please make a pr?

**Comment by PistonY** [comment]
Fix in master.
https://github.com/PistonY/torch-toolbox/blob/c9070e6e643207711ad9200ae34d239fedc7e828/torchtoolbox/data/lmdb_dataset.py#L19
